### ISSUE TITLE
Any plan to integrate with official repos?

### ISSUE THREAD

**Issue by carun** [uniqueck/asciidoctorj-liquibase-extension#4]
This is a nifty extension. Is there a way to integrate this with asciidoctor without using maven plugin?

**Comment by uniqueck** [comment]
Hi carun thanks for this. I think it will work, I investigate for a little example.

**Comment by carun** [comment]
Thanks @uniqueck please let me know how it goes.

**Comment by uniqueck** [comment]
Hi @carun, sorry for my late reply. What is you plan? Do you want to integrate it with the java api from asciidoctorj? So all what you have to do, is to declare an dependency to this extension. This extension is self registered over the SPI mechanism from Java. You have to configure and instantiate an Asciidoctor instance. For a working example have look at the tests.
Let me know if you need more help.

**Comment by uniqueck** [comment]
Hi @carun, today a new version 0.1.1 is release to maven central. Do you need some help, if not i will close this issue in the next few weeks.

**Comment by carun** [comment]
Thanks @uniqueck let me try that. I will close this issue for now.
