### ISSUE TITLE
Picture too big

### ISSUE THREAD

**Issue by sebastian-elkhouri** [uniqueck/asciidoctorj-liquibase-extension#5]
Hello,

When I try to generate a diagram for a big changeset file with many tables, the picture is cut off and not everything appears. Is there a way to fix that ?

**Comment by uniqueck** [comment]
Hi @sebastian-elkhouri,

i think we add an property to control page splitting option from plantuml.
What do you mean, do you try it without this extension?

**Comment by sebastian-elkhouri** [comment]
Thanks for the prompt response. I am not really sure what you meant by trying it without the extension. To clarify my point, I have attached an image. As you can see in the bottom right, one table's name is cut off as indicated by the purple arrow, and there is a line going to the right as indicated by the red arrow. This means that there are some tables in the right side of the image that are not showing because they don't fit in the image. I also verified that : when I removed some tables on the left side, the tables that did not fit in the image now fit and are visible. 

![diag-e778232b60cf4841ff66cf0e66a2ab3d](https://user-images.githubusercontent.com/80093276/110295588-f5104300-7ff9-11eb-9d01-8906b4daa06e.png)

**Comment by uniqueck** [comment]
Thanks for the clarification. What I meant without the extension is, do you create the plantuml file from scratch and experiment with the available settings from plantuml. So maybe it is possible that we can introduce some of the settings to the extension.

**Comment by sebastian-elkhouri** [comment]
I was reading online and it seems if you set PLANTUML_LIMIT_SIZE to 8192 as an environment variable, the picture will not be cut off. I tried it and it seems to work. But I feel a better solution would be generating an svg file instead of a png file. Is that currently possible ? I am not very familiar with asciidoctor and how your extension integrates with it.

**Comment by sebastian-elkhouri** [comment]
It seems setting PLANTUML_LIMIT_SIZE to 8192 before running the extension makes the picture fit. However, I feel a better solution would be generating the image as svg instead of png. Do you know if that's possible ? I am not very familiar with asciidoctor and how your extension integrates with it.

**Comment by uniqueck** [comment]
Ok I try something and come back to you.

**Comment by sebastian-elkhouri** [comment]
Hello, I found the way to do it. I added two attributes for the macro: file name and output format (png or svg). I created a pull request if you can check it out.

**Comment by uniqueck** [comment]
Code is merged. Sorry for the delay.

**Comment by uniqueck** [comment]
For a new release, i have to check what is going wrong on circleci. I came back to you when it is fixed.

**Comment by uniqueck** [comment]
Hi @sebastian-elkhouri, sorry for the late reply, but i thought i use the time to migrate away from bintray to maven central. So new version 0.1.1 is deployed at maven central. In one or two hours you can find the new release in maven central, it needs some time for the search index update. I close this issue for now, if something is wrong, reopen this issue.
