### ISSUE TITLE
[FEATURE] Support for YAML based changesets and changelogs

### ISSUE THREAD

**Issue by Ahbrown41** [uniqueck/asciidoctorj-liquibase-extension#8]
### Is your feature request related to a problem?
I am trying to integrate with the tool now and all of our files are in YAML vs XML as it feels much easier to read to me.
I see the tool does not support YAML and I was wondering if you would consider updating?

### What solution would you like?
Support for normal YAML files for changesets and changelogs.

### What alternatives have you considered?
I looked at converting our files to XML at compile time but do not thing that can be done in a lossless way.

### Do you have any additional context?
Cool tool, would love to see PlantUML or Mermaid docs as well.  Especially not that Github support Mermaid.

**Comment by uniqueck** [comment]
@Ahbrown41  is that still needed? I switched to asciidoctor.js so I reimplement the same extension in based on node.js. Have a look at https://github.com/uniqueck/asciidoctor-liquibase.

**Comment by Ahbrown41** [comment]
Hey @uniqueck I likely do not although now need to do Node in our tool chain.  Will check out the other tool.  Thanks!
